### PR TITLE
Fixup of injections, RFing of dump(), etc.

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
now it fails "interestingly": 

```
$> DUECREDIT_ENABLE=True venv/bin/python examples/example_scipy.py         
2015-07-23 14:04:31,984 [WARNING] DueCredit internal failure while running <function cite at 0x7f44b91ea488>: __init__() got an unexpected keyword argument 'level'. Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:73)
DueCredit Report:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/yoh/proj/duecredit/duecredit/__init__.py", line 48, in crap
    _due_summary.dump()
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 341, in dump
    output.dump()
  File "/home/yoh/proj/duecredit/duecredit/io.py", line 70, in dump
    if citation.cites_module:
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 92, in cites_module
    return self.path and ':' not in self.path
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 80, in path
    return self._path
AttributeError: 'Citation' object has no attribute '_path'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/yoh/proj/duecredit/duecredit/__init__.py", line 48, in crap
    _due_summary.dump()
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 341, in dump
    output.dump()
  File "/home/yoh/proj/duecredit/duecredit/io.py", line 70, in dump
    if citation.cites_module:
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 92, in cites_module
    return self.path and ':' not in self.path
  File "/home/yoh/proj/duecredit/duecredit/collector.py", line 80, in path
    return self._path
AttributeError: 'Citation' object has no attribute '_path'
```

so I will look into it and will update this PR

**Comment by yarikoptic** [comment]
actually that is a boring one -- just to remind us to move away from just pickling the beast or to at least provide proper `__reduce__` and `__setstate__` - it was loading a stale version which didn't have _path defined.   Now it ran into a "proper" issue -- `level` is gone, replaced with `path`.

**Comment by yarikoptic** [comment]
and again not a proper one./.. sorry for all the noise... ;-)  now I am at a really proper bug!

**Comment by yarikoptic** [comment]
This is somewhat mad changes -- I do not expect you to appreciate or comprehend them, but would be nice if you review/comment or better just improve ;)  Apparently all the injection business appeared to be a bit trickier and there is more work to be done:  should be optimized, otherwise penalty might be quite high. Tests should be extended as well.  But before anything -- could you try it - does it work at all for you?

I at least get the following:

```
$> rm .duecredit.p; DUECREDIT_ENABLE=True venv/bin/python examples/example_scipy.py
I: Simulating 4 blobs
I: Done clustering 4 blobs
DueCredit Report:

0 modules cited
0 functions cited
[1] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link
        cluster method. The Computer Journal, 16(1), pp.30–34.
```

Just needs a fix up I guess the logic somewhere in deciding all the modules etc citations

**Comment by yarikoptic** [comment]
I have found what is wrong with citations of modules -- will fix up later and buzz you.

**Comment by mvdoc** [comment]
Thanks! Yes I get the same output as yours. I'll start looking into it and try to comprehend it.

BTW, did you PR on my fork on purpose?

**Comment by yarikoptic** [comment]
Yeap, for review and merge

**Comment by yarikoptic** [comment]
Ok -- we are back on track!!!

```
$> rm .duecredit.p; DUECREDIT_ALLOW_FAIL=1 DUECREDIT_ENABLE=True venv/bin/python examples/example_scipy.py
I: Simulating 4 blobs
I: Done clustering 4 blobs
DueCredit Report:
- scipy (v None) [1]
  - scipy.cluster.hierarchy:linkage (Single linkage hierarchical clustering) [2]
- numpy (v None) [3]

2 modules cited
1 functions cited

References
----------

[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
[2] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link
        cluster method. The Computer Journal, 16(1), pp.30–34.
[3] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.

$> DUECREDIT_REPORT_TAGS=implementation venv/bin/duecredit summary                                                                             
DueCredit Report:
- scipy (v None) [1]
  - scipy.cluster.hierarchy:linkage (Single linkage hierarchical clustering) [2]

1 modules cited
1 functions cited

References
----------

[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
[2] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link
        cluster method. The Computer Journal, 16(1), pp.30–34.

$> DUECREDIT_REPORT_TAGS=* venv/bin/duecredit summary              
DueCredit Report:
- scipy (v None) [1, 2, 3, 4, 5, 6, 7, 8]
  - scipy.cluster.hierarchy:linkage (Single linkage hierarchical clustering) [9]
- numpy (v None) [10]

2 modules cited
1 functions cited

References
----------

[1] Sokal, R.R., Michener, C.D. & University of Kansas, 1958. A Statistical Method for Evaluating Systematic Relationships, University of Kansas.
[2] Jain, A.K. & Dubes, R.C., 1988. Algorithms for clustering data, Prentice-Hall, Inc..
[3] Johnson, S.C., 1967. Hierarchical clustering schemes. Psychometrika, 32(3), pp.241–254.
[4] Sneath, P.H. & Sokal, R.R., 1962. Numerical taxonomy. Nature, 193(4818), pp.855–860.
[5] Fisher, R.A., 1936. The use of multiple measurements in taxonomic problems. Annals of eugenics, 7(2), pp.179–188.
[6] Edelbrock, C., 1979. Mixture model tests of hierarchical clustering algorithms:
            the problem of classifying everybody. Multivariate Behavioral Research, 14(3), pp.367–384.
[7] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
[8] Batagelj, V. & Bren, M., 1995. Comparing resemblance measures. Journal of classification, 12(1), pp.73–90.
[9] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link
        cluster method. The Computer Journal, 16(1), pp.30–34.
[10] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
```

Please review how I have changed `dump()`.  But it needs more refinement.  We should do model in three levels (package -> module -> obj) instead of two (package -> obj) and model logic and view both should be adjusted for that.
But the point is that injections should work now, we just need to add more and test more.

After getting familiarized, merge and I will then merge your PR as well (which will get updated with these changes I believe).  We could even tag this state as a next release

**Comment by yarikoptic** [comment]
BTW -- please enable travis for your clone -- otherwise it doesn't run tests on PRs against your clone

**Comment by mvdoc** [comment]
travis is now active -- if you want push some random stuff to make it run

**Comment by yarikoptic** [comment]
now even versions for modules should somewhat work ;)

```
$> rm .duecredit.p; DUECREDIT_ALLOW_FAIL=1 DUECREDIT_ENABLE=True venv/bin/python examples/example_scipy.py
I: Simulating 4 blobs                                                                     
I: Done clustering 4 blobs
DueCredit Report:
- scipy (v 0.14.1) [1]
  - scipy.cluster.hierarchy:linkage (Single linkage hierarchical clustering) [2]
- numpy (v 1.8.2) [3]
...
```

I guess I will just merge the beats into the master, tag new "release",  and we then proceed from there

**Comment by yarikoptic** [comment]
travis failed since we need tags on remote so version could be generated, ie at some point push some tags to your clone ;)

**Pull request closed without merging**
